#!/usr/bin/env node
// Audio source check: every URL the app can play.
//  - Audio Only reciters: all 114 surah files (HTTP status, audio content-type,
//    playable duration via ffprobe, duration plausible vs the word-sync masters).
//  - Word Sync reciters: all 114 paired quranicaudio masters (status + duration
//    vs the timing dataset's own duration).
//  - Juz per-ayah (everyayah): every Surah's ayah 1 and each Juz's first/last ayah.
//  - Maher full-Juz files.
// Writes scripts/qa/results/audio-sources.json and regenerates
// src/lib/data/reciterAvailability.ts (which Surahs each Audio Only reciter
// really has), so the app never offers a file that isn't there.
//
// Usage: node scripts/qa/audio-sources.cjs [--no-probe]
const fs = require("fs");
const path = require("path");
const { execFile } = require("child_process");
const { R, Q, ROOT, nativeFetch } = require("./lib/load.cjs");

const PROBE = !process.argv.includes("--no-probe");
const OUT = path.join(ROOT, "scripts/qa/results");
fs.mkdirSync(OUT, { recursive: true });

const probe = (url) =>
  new Promise((res) =>
    execFile("ffprobe", ["-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", url], { timeout: 90000 }, (e, o) =>
      res(e ? null : Number(String(o).trim()) || null)
    )
  );
async function head(url) {
  for (let i = 0; i < 3; i++) {
    try {
      const r = await nativeFetch(url, { method: "HEAD", redirect: "follow" });
      if (r.status === 429 || r.status >= 500) throw new Error(`status ${r.status}`);
      return { status: r.status, type: r.headers.get("content-type") || "", len: Number(r.headers.get("content-length") || 0) };
    } catch (e) {
      if (i === 2) return { status: 0, err: String(e.cause?.code || e.message) };
      await new Promise((r) => setTimeout(r, 800 * (i + 1)));
    }
  }
}
async function pool(items, n, fn) {
  const out = new Array(items.length);
  let i = 0;
  await Promise.all(Array.from({ length: n }, async () => { while (i < items.length) { const k = i++; out[k] = await fn(items[k]); } }));
  return out;
}

(async () => {
  const t0 = Date.now();
  const SYNC = R.QURAN_RECITERS.filter((r) => R.reciterHasWordTiming(r));
  const ONLY = R.QURAN_RECITERS.filter((r) => !R.reciterHasWordTiming(r));

  // Word-sync masters: status + real duration vs dataset duration.
  const syncJobs = [];
  for (const r of SYNC) for (let s = 1; s <= 114; s++) syncJobs.push({ r: r.id, s, url: R.buildReciterSurahUrl(r, s) });
  const sync = await pool(syncJobs, 16, async (j) => {
    const h = await head(j.url);
    const data = JSON.parse(fs.readFileSync(path.join(ROOT, "public/data/quran-timings", j.r, `${j.s}.json`), "utf8"));
    const real = h.status === 200 && PROBE ? await probe(j.url) : null;
    return { ...j, ...h, real, dataDur: data.durationSeconds, drift: real ? +(real - data.durationSeconds).toFixed(2) : null };
  });
  // Median real duration of each surah across the word-sync masters.
  const med = {};
  for (let s = 1; s <= 114; s++) {
    const d = sync.filter((x) => x.s === s && x.real).map((x) => x.real).sort((a, b) => a - b);
    med[s] = d.length ? d[Math.floor(d.length / 2)] : null;
  }

  // Audio-only: every surah.
  const onlyJobs = [];
  for (const r of ONLY) for (let s = 1; s <= 114; s++) onlyJobs.push({ r: r.id, s, url: R.buildReciterSurahUrl(r, s) });
  const only = await pool(onlyJobs, 16, async (j) => {
    const h = await head(j.url);
    const audio = h.status === 200 && /audio|mpeg|octet-stream/i.test(h.type);
    const real = audio && PROBE ? await probe(j.url) : null;
    const ratio = real && med[j.s] ? +(real / med[j.s]).toFixed(2) : null;
    const ok = audio && (!PROBE || (real !== null && ratio !== null && ratio > 0.4 && ratio < 10));
    return { ...j, ...h, real, ratio, ok };
  });

  // Juz sources.
  const juzJobs = [];
  for (const jz of Q.QURAN_JUZ) juzJobs.push({ kind: "maher-full-juz", j: jz.id, url: jz.audioUrl });
  for (const rid of Object.keys(R.EVERYAYAH_FOLDERS)) {
    for (let j = 1; j <= 30; j++) {
      const u = Q.buildJuzAyahUrls(j, rid);
      juzJobs.push({ kind: "everyayah-juz-first", r: rid, j, url: u[0] }, { kind: "everyayah-juz-last", r: rid, j, url: u[u.length - 1] });
    }
    for (let s = 1; s <= 114; s++) juzJobs.push({ kind: "everyayah-ayah1", r: rid, s, url: `https://everyayah.com/data/${R.EVERYAYAH_FOLDERS[rid]}/${String(s).padStart(3, "0")}001.mp3` });
  }
  const juz = await pool(juzJobs, 16, async (j) => ({ ...j, ...(await head(j.url)) }));

  // Availability of Audio Only reciters (only list the ones with gaps).
  const avail = {};
  for (const r of ONLY) {
    const have = only.filter((x) => x.r === r.id && x.ok).map((x) => x.s);
    if (have.length < 114) avail[r.id] = have;
  }
  const ts = `/**
 * GENERATED by scripts/qa/audio-sources.cjs — do not edit by hand.
 * Surahs each Audio Only reciter really has on its mp3quran.net server
 * (HTTP 200, audio content, playable length). Reciters not listed have all 114.
 * An empty list = the server publishes none of them (reciter unavailable).
 * Checked: ${new Date().toISOString().slice(0, 10)}
 */
export const AUDIO_ONLY_AVAILABLE_SURAHS: Record<string, number[]> = ${JSON.stringify(avail, null, 2)};
`;
  fs.writeFileSync(path.join(ROOT, "src/lib/data/reciterAvailability.ts"), ts);

  const summary = {
    generated: new Date().toISOString(),
    secs: Math.round((Date.now() - t0) / 1000),
    wordSyncStreams: sync.length,
    wordSyncHttpFailures: sync.filter((x) => x.status !== 200).map((x) => `${x.r}/${x.s} ${x.status}`),
    wordSyncDurationDrift2s: sync.filter((x) => x.drift !== null && Math.abs(x.drift) > 2).map((x) => `${x.r}/${x.s} real ${x.real} data ${x.dataDur} Δ${x.drift}`),
    audioOnlyChecked: only.length,
    audioOnlyUnavailable: Object.fromEntries(Object.entries(avail).map(([k, v]) => [k, 114 - v.length])),
    audioOnlyBad: only.filter((x) => !x.ok).length,
    juzChecked: juz.length,
    juzHttpFailures: juz.filter((x) => x.status !== 200).map((x) => `${x.kind} ${x.r || ""} ${x.j ? "j" + x.j : ""}${x.s ? "s" + x.s : ""} ${x.status}`),
  };
  fs.writeFileSync(path.join(OUT, "audio-sources.json"), JSON.stringify({ summary, sync, only, juz }, null, 1));
  console.log(JSON.stringify(summary, null, 1));
})();
