import type { Strings } from "@/lib/uiLang";

/** UI strings (home): English key → other languages (missing → English). */
const strings: Strings = {
  // ── Greeting (before the first play) ──
  "As-salamu alaykum": { ta: "அஸ்ஸலாமு அலைக்கும்", ur: "السلام علیکم", ml: "അസ്സലാമു അലൈക്കും", hi: "अस्सलामु अलैकुम", id: "Assalamu'alaikum", bn: "আসসালামু আলাইকুম", tr: "Esselâmü aleyküm", fr: "As-salamu alaykum", ms: "Assalamualaikum" },
  "Peace be upon you": { ta: "உங்கள் மீது சாந்தி உண்டாவதாக", ur: "آپ پر سلامتی ہو", ml: "നിങ്ങൾക്ക് സമാധാനം ഉണ്ടാകട്ടെ", hi: "आप पर शांति हो", id: "Semoga keselamatan tercurah kepadamu", bn: "আপনার উপর শান্তি বর্ষিত হোক", tr: "Selam üzerinize olsun", fr: "Que la paix soit sur vous", ms: "Semoga kesejahteraan ke atas kamu" },

  // ── Notices ──
  "No internet connection. The recitation continues once you're back online.": { ta: "இணையம் இல்லை. இணைப்பு வந்ததும் ஓதல் தொடரும்.", ur: "انٹرنیٹ کنکشن نہیں۔ کنکشن بحال ہوتے ہی تلاوت جاری رہے گی۔", ml: "ഇന്റർനെറ്റ് ഇല്ല. കണക്ഷൻ തിരികെ വന്നാൽ പാരായണം തുടരും.", hi: "इंटरनेट कनेक्शन नहीं है। कनेक्शन लौटते ही तिलावत जारी रहेगी।", id: "Tidak ada koneksi internet. Bacaan berlanjut setelah Anda kembali online.", bn: "ইন্টারনেট সংযোগ নেই। সংযোগ ফিরলেই তিলাওয়াত চলবে।", tr: "İnternet bağlantısı yok. Bağlantı gelince tilavet devam eder.", fr: "Pas de connexion Internet. La récitation reprendra dès votre retour en ligne.", ms: "Tiada sambungan internet. Bacaan diteruskan sebaik sahaja anda kembali dalam talian." },
  "Back online": { ta: "இணையம் மீண்டும் இணைந்தது", ur: "انٹرنیٹ بحال ہو گیا", ml: "വീണ്ടും ഓൺലൈനായി", hi: "फिर से ऑनलाइन", id: "Kembali online", bn: "আবার অনলাইনে", tr: "Yeniden çevrimiçi", fr: "De nouveau en ligne", ms: "Kembali dalam talian" },
  "Juz {juz} isn't available in {reciter}'s voice. Choose another reciter for Juz (e.g. Maher Al-Muaiqly).": { ta: "{reciter} — ஜுஸ்உ {juz} இந்தக் காரியின் குரலில் இல்லை. ஜுஸ்உ-க்கு வேறு காரியைத் தேர்ந்தெடுக்கவும் (எ.கா. Maher Al-Muaiqly).", ur: "پارہ {juz} {reciter} کی آواز میں دستیاب نہیں۔ پارے کے لیے کوئی اور قاری چنیں (مثلاً Maher Al-Muaiqly)۔", ml: "ജുസ്‌അ് {juz} {reciter}-ന്റെ ശബ്ദത്തിൽ ലഭ്യമല്ല. ജുസ്‌അിന് മറ്റൊരു ഖാരിയെ തിരഞ്ഞെടുക്കുക (ഉദാ. Maher Al-Muaiqly).", hi: "पारा {juz} {reciter} की आवाज़ में उपलब्ध नहीं है। पारे के लिए कोई और क़ारी चुनें (जैसे Maher Al-Muaiqly)।", id: "Juz {juz} tidak tersedia dalam suara {reciter}. Pilih qari lain untuk Juz (mis. Maher Al-Muaiqly).", bn: "পারা {juz} {reciter}-এর কণ্ঠে নেই। পারার জন্য অন্য ক্বারী বেছে নিন (যেমন Maher Al-Muaiqly)।", tr: "Cüz {juz}, {reciter} sesinde mevcut değil. Cüz için başka bir kârî seçin (ör. Maher Al-Muaiqly).", fr: "Le Juz {juz} n'est pas disponible avec la voix de {reciter}. Choisissez un autre récitateur pour le Juz (ex. Maher Al-Muaiqly).", ms: "Juzuk {juz} tiada dalam suara {reciter}. Pilih qari lain untuk Juzuk (cth. Maher Al-Muaiqly)." },
  "{reciter} is Audio Only — {what} will play again from the beginning.": { ta: "{reciter} — ஒலி மட்டும். {what} முதல் ஆயத்திலிருந்து மீண்டும் ஒலிக்கும்.", ur: "{reciter} صرف آڈیو ہے — {what} شروع سے دوبارہ چلے گا۔", ml: "{reciter} ഓഡിയോ മാത്രം — {what} തുടക്കം മുതൽ വീണ്ടും പ്ലേ ചെയ്യും.", hi: "{reciter} केवल ऑडियो है — {what} शुरू से फिर चलेगा।", id: "{reciter} hanya audio — {what} diputar ulang dari awal.", bn: "{reciter} শুধু অডিও — {what} শুরু থেকে আবার চলবে।", tr: "{reciter} yalnızca ses — {what} baştan yeniden çalacak.", fr: "{reciter} est en audio seul — {what} reprendra depuis le début.", ms: "{reciter} audio sahaja — {what} dimainkan semula dari awal." },
  "The Surah": { ta: "இந்த சூரா", ur: "سورۃ", ml: "സൂറ", hi: "सूरह", id: "Surah ini", bn: "সূরাটি", tr: "Sure", fr: "La sourate", ms: "Surah ini" },
  "{reciter} has no Juz recording — playing the Surah instead.": { ta: "{reciter} — ஜுஸ்உ ஓதல் இல்லை; அதே சூரா முழுமையாக ஒலிக்கும்.", ur: "{reciter} کی پارے کی ریکارڈنگ نہیں — اس کے بجائے سورۃ چل رہی ہے۔", ml: "{reciter}-ന് ജുസ്‌അ് റെക്കോർഡിംഗ് ഇല്ല — പകരം സൂറ പ്ലേ ചെയ്യുന്നു.", hi: "{reciter} की पारे की रिकॉर्डिंग नहीं है — इसके बजाय सूरह चल रही है।", id: "{reciter} tidak punya rekaman Juz — memutar Surah sebagai gantinya.", bn: "{reciter}-এর পারার রেকর্ডিং নেই — তার বদলে সূরা চলছে।", tr: "{reciter} için cüz kaydı yok — bunun yerine sure çalınıyor.", fr: "{reciter} n'a pas d'enregistrement du Juz — lecture de la sourate à la place.", ms: "{reciter} tiada rakaman Juzuk — memainkan Surah sebagai ganti." },
  "Word Sync isn't available for this Surah in {reciter}'s recording — audio only.": { ta: "{reciter} — இந்த சூராவின் ஓதலுக்குச் சொல் ஒத்திசைவு இல்லை; ஒலி மட்டும்.", ur: "{reciter} کی ریکارڈنگ میں اس سورۃ کے لیے لفظی ہم آہنگی دستیاب نہیں — صرف آڈیو۔", ml: "{reciter}-ന്റെ റെക്കോർഡിംഗിൽ ഈ സൂറയ്ക്ക് വേഡ് സിങ്ക് ഇല്ല — ഓഡിയോ മാത്രം.", hi: "{reciter} की रिकॉर्डिंग में इस सूरह के लिए शब्द-सिंक उपलब्ध नहीं — केवल ऑडियो।", id: "Sinkron kata tidak tersedia untuk Surah ini dalam rekaman {reciter} — hanya audio.", bn: "{reciter}-এর রেকর্ডিংয়ে এই সূরার শব্দ-সিঙ্ক নেই — শুধু অডিও।", tr: "{reciter} kaydında bu sure için kelime senkronu yok — yalnızca ses.", fr: "La synchro des mots n'est pas disponible pour cette sourate dans l'enregistrement de {reciter} — audio seul.", ms: "Segerak perkataan tiada untuk Surah ini dalam rakaman {reciter} — audio sahaja." },
  "This is Juz {other}. Juz {juz} starts mid-page, at {at}.": { ta: "இது ஜுஸ்உ {other}. ஜுஸ்உ {juz} இந்தப் பக்கத்தின் நடுவில் {at}-இல் தொடங்குகிறது.", ur: "یہ پارہ {other} ہے۔ پارہ {juz} صفحے کے بیچ میں، {at} سے شروع ہوتا ہے۔", ml: "ഇത് ജുസ്‌അ് {other} ആണ്. ജുസ്‌അ് {juz} ഈ പേജിന്റെ നടുവിൽ, {at}-ൽ തുടങ്ങുന്നു.", hi: "यह पारा {other} है। पारा {juz} पृष्ठ के बीच में, {at} से शुरू होता है।", id: "Ini Juz {other}. Juz {juz} dimulai di tengah halaman, pada {at}.", bn: "এটি পারা {other}। পারা {juz} পৃষ্ঠার মাঝখানে, {at}-এ শুরু হয়।", tr: "Bu Cüz {other}. Cüz {juz} sayfanın ortasında, {at} ile başlar.", fr: "Ceci est le Juz {other}. Le Juz {juz} commence en milieu de page, à {at}.", ms: "Ini Juzuk {other}. Juzuk {juz} bermula di tengah halaman, pada {at}." },
  "This is Juz {other}. Juz {juz} ends mid-page, at {at}.": { ta: "இது ஜுஸ்உ {other}. ஜுஸ்உ {juz} இந்தப் பக்கத்தின் நடுவில் {at}-இல் முடிகிறது.", ur: "یہ پارہ {other} ہے۔ پارہ {juz} صفحے کے بیچ میں، {at} پر ختم ہوتا ہے۔", ml: "ഇത് ജുസ്‌അ് {other} ആണ്. ജുസ്‌അ് {juz} ഈ പേജിന്റെ നടുവിൽ, {at}-ൽ അവസാനിക്കുന്നു.", hi: "यह पारा {other} है। पारा {juz} पृष्ठ के बीच में, {at} पर समाप्त होता है।", id: "Ini Juz {other}. Juz {juz} berakhir di tengah halaman, pada {at}.", bn: "এটি পারা {other}। পারা {juz} পৃষ্ঠার মাঝখানে, {at}-এ শেষ হয়।", tr: "Bu Cüz {other}. Cüz {juz} sayfanın ortasında, {at} ile biter.", fr: "Ceci est le Juz {other}. Le Juz {juz} se termine en milieu de page, à {at}.", ms: "Ini Juzuk {other}. Juzuk {juz} berakhir di tengah halaman, pada {at}." },
  "This is {other}. {surah} starts mid-page.": { ta: "இது {other}. {surah} இந்தப் பக்கத்தின் நடுவில் தொடங்குகிறது.", ur: "یہ {other} ہے۔ {surah} صفحے کے بیچ سے شروع ہوتی ہے۔", ml: "ഇത് {other} ആണ്. {surah} ഈ പേജിന്റെ നടുവിൽ തുടങ്ങുന്നു.", hi: "यह {other} है। {surah} पृष्ठ के बीच से शुरू होती है।", id: "Ini {other}. {surah} dimulai di tengah halaman.", bn: "এটি {other}। {surah} পৃষ্ঠার মাঝখানে শুরু হয়।", tr: "Bu {other}. {surah} sayfanın ortasında başlar.", fr: "Ceci est {other}. {surah} commence en milieu de page.", ms: "Ini {other}. {surah} bermula di tengah halaman." },
  "This is {other}. {surah} ends mid-page.": { ta: "இது {other}. {surah} இந்தப் பக்கத்தின் நடுவில் முடிகிறது.", ur: "یہ {other} ہے۔ {surah} صفحے کے بیچ میں ختم ہوتی ہے۔", ml: "ഇത് {other} ആണ്. {surah} ഈ പേജിന്റെ നടുവിൽ അവസാനിക്കുന്നു.", hi: "यह {other} है। {surah} पृष्ठ के बीच में समाप्त होती है।", id: "Ini {other}. {surah} berakhir di tengah halaman.", bn: "এটি {other}। {surah} পৃষ্ঠার মাঝখানে শেষ হয়।", tr: "Bu {other}. {surah} sayfanın ortasında biter.", fr: "Ceci est {other}. {surah} se termine en milieu de page.", ms: "Ini {other}. {surah} berakhir di tengah halaman." },
  "Link copied · {title}": { ta: "இணைப்பு நகலெடுக்கப்பட்டது · {title}", ur: "لنک کاپی ہو گیا · {title}", ml: "ലിങ്ക് പകർത്തി · {title}", hi: "लिंक कॉपी हो गया · {title}", id: "Tautan disalin · {title}", bn: "লিংক কপি হয়েছে · {title}", tr: "Bağlantı kopyalandı · {title}", fr: "Lien copié · {title}", ms: "Pautan disalin · {title}" },

  // ── Home controls ──
  "Exit reading mode": { ta: "வாசிப்பு முறையிலிருந்து வெளியேறு", ur: "مطالعہ موڈ سے باہر نکلیں", ml: "വായന മോഡിൽ നിന്ന് പുറത്തുകടക്കുക", hi: "पढ़ने का मोड छोड़ें", id: "Keluar dari mode baca", bn: "পড়ার মোড থেকে বের হন", tr: "Okuma modundan çık", fr: "Quitter le mode lecture", ms: "Keluar mod bacaan" },
  "Reading mode": { ta: "வாசிப்பு முறை", ur: "مطالعہ موڈ", ml: "വായന മോഡ്", hi: "पढ़ने का मोड", id: "Mode baca", bn: "পড়ার মোড", tr: "Okuma modu", fr: "Mode lecture", ms: "Mod bacaan" },
  Continue: { ta: "தொடர்க", ur: "جاری رکھیں", ml: "തുടരുക", hi: "जारी रखें", id: "Lanjutkan", bn: "চালিয়ে যান", tr: "Devam et", fr: "Reprendre", ms: "Teruskan" },
  "Image mode": { ta: "பட முறை", ur: "تصویر موڈ", ml: "ചിത്ര മോഡ്", hi: "चित्र मोड", id: "Mode gambar", bn: "ছবি মোড", tr: "Görsel modu", fr: "Mode image", ms: "Mod imej" },
  "Video mode": { ta: "காணொளி முறை", ur: "ویڈیو موڈ", ml: "വീഡിയോ മോഡ്", hi: "वीडियो मोड", id: "Mode video", bn: "ভিডিও মোড", tr: "Video modu", fr: "Mode vidéo", ms: "Mod video" },
  "Switch to Image Mode": { ta: "பட முறைக்கு மாறு", ur: "تصویر موڈ پر جائیں", ml: "ചിത്ര മോഡിലേക്ക് മാറുക", hi: "चित्र मोड पर जाएँ", id: "Beralih ke mode gambar", bn: "ছবি মোডে যান", tr: "Görsel moduna geç", fr: "Passer en mode image", ms: "Tukar ke mod imej" },
  "Switch to Video Mode": { ta: "காணொளி முறைக்கு மாறு", ur: "ویڈیو موڈ پر جائیں", ml: "വീഡിയോ മോഡിലേക്ക് മാറുക", hi: "वीडियो मोड पर जाएँ", id: "Beralih ke mode video", bn: "ভিডিও মোডে যান", tr: "Video moduna geç", fr: "Passer en mode vidéo", ms: "Tukar ke mod video" },
  "Video Mode Active (Click to switch to Image Mode)": { ta: "காணொளி முறை (பட முறைக்கு மாற அழுத்தவும்)", ur: "ویڈیو موڈ (تصویر موڈ کے لیے دبائیں)", ml: "വീഡിയോ മോഡ് (ചിത്ര മോഡിലേക്ക് മാറാൻ അമർത്തുക)", hi: "वीडियो मोड (चित्र मोड के लिए दबाएँ)", id: "Mode video aktif (klik untuk beralih ke mode gambar)", bn: "ভিডিও মোড চালু (ছবি মোডে যেতে চাপুন)", tr: "Video modu açık (görsel moduna geçmek için tıklayın)", fr: "Mode vidéo actif (cliquez pour passer en mode image)", ms: "Mod video aktif (klik untuk tukar ke mod imej)" },
  "Image Mode Active (Click to switch to Video Mode)": { ta: "பட முறை (காணொளி முறைக்கு மாற அழுத்தவும்)", ur: "تصویر موڈ (ویڈیو موڈ کے لیے دبائیں)", ml: "ചിത്ര മോഡ് (വീഡിയോ മോഡിലേക്ക് മാറാൻ അമർത്തുക)", hi: "चित्र मोड (वीडियो मोड के लिए दबाएँ)", id: "Mode gambar aktif (klik untuk beralih ke mode video)", bn: "ছবি মোড চালু (ভিডিও মোডে যেতে চাপুন)", tr: "Görsel modu açık (video moduna geçmek için tıklayın)", fr: "Mode image actif (cliquez pour passer en mode vidéo)", ms: "Mod imej aktif (klik untuk tukar ke mod video)" },
  "Remove bookmark": { ta: "புக்மார்க்கை நீக்கு", ur: "بُک مارک ہٹائیں", ml: "ബുക്ക്മാർക്ക് നീക്കുക", hi: "बुकमार्क हटाएँ", id: "Hapus penanda", bn: "বুকমার্ক সরান", tr: "Yer imini kaldır", fr: "Retirer le signet", ms: "Buang penanda" },
  "Add bookmark": { ta: "புக்மார்க் சேர்", ur: "بُک مارک لگائیں", ml: "ബുക്ക്മാർക്ക് ചേർക്കുക", hi: "बुकमार्क जोड़ें", id: "Tambah penanda", bn: "বুকমার্ক যোগ করুন", tr: "Yer imi ekle", fr: "Ajouter un signet", ms: "Tambah penanda" },
  Share: { ta: "பகிர்", ur: "شیئر کریں", ml: "പങ്കിടുക", hi: "शेयर करें", id: "Bagikan", bn: "শেয়ার করুন", tr: "Paylaş", fr: "Partager", ms: "Kongsi" },

  // ── Header: translation sheet ──
  Translation: { ta: "மொழிபெயர்ப்பு", ur: "ترجمہ", ml: "പരിഭാഷ", hi: "अनुवाद", id: "Terjemahan", bn: "অনুবাদ", tr: "Meal", fr: "Traduction", ms: "Terjemahan" },
  "Translation: {name} — change": { ta: "மொழிபெயர்ப்பு: {name} — மாற்று", ur: "ترجمہ: {name} — بدلیں", ml: "പരിഭാഷ: {name} — മാറ്റുക", hi: "अनुवाद: {name} — बदलें", id: "Terjemahan: {name} — ubah", bn: "অনুবাদ: {name} — বদলান", tr: "Meal: {name} — değiştir", fr: "Traduction : {name} — changer", ms: "Terjemahan: {name} — tukar" },
  "Translation: off — choose a language": { ta: "மொழிபெயர்ப்பு: இல்லை — ஒரு மொழியைத் தேர்ந்தெடு", ur: "ترجمہ: بند — زبان چنیں", ml: "പരിഭാഷ: ഓഫ് — ഒരു ഭാഷ തിരഞ്ഞെടുക്കുക", hi: "अनुवाद: बंद — भाषा चुनें", id: "Terjemahan: mati — pilih bahasa", bn: "অনুবাদ: বন্ধ — একটি ভাষা বেছে নিন", tr: "Meal: kapalı — bir dil seçin", fr: "Traduction : désactivée — choisir une langue", ms: "Terjemahan: mati — pilih bahasa" },
  "Choose the translation language": { ta: "மொழிபெயர்ப்பு மொழியைத் தேர்ந்தெடு", ur: "ترجمے کی زبان چنیں", ml: "പരിഭാഷാ ഭാഷ തിരഞ്ഞെടുക്കുക", hi: "अनुवाद की भाषा चुनें", id: "Pilih bahasa terjemahan", bn: "অনুবাদের ভাষা বেছে নিন", tr: "Meal dilini seçin", fr: "Choisir la langue de traduction", ms: "Pilih bahasa terjemahan" },
  "Choose the meaning language": { ta: "பொருள் மொழியைத் தேர்ந்தெடுக்கவும்", ur: "معنی کی زبان چنیں", ml: "അർത്ഥത്തിന്റെ ഭാഷ തിരഞ്ഞെടുക്കുക", hi: "अर्थ की भाषा चुनें", id: "Pilih bahasa makna", bn: "অর্থের ভাষা বেছে নিন", tr: "Anlam dilini seçin", fr: "Choisir la langue du sens", ms: "Pilih bahasa makna" },
  "Translation on — turn off (Arabic only)": { ta: "மொழிபெயர்ப்பு உள்ளது — நிறுத்து (அரபு மட்டும்)", ur: "ترجمہ آن — بند کریں (صرف عربی)", ml: "പരിഭാഷ ഓൺ — ഓഫാക്കുക (അറബി മാത്രം)", hi: "अनुवाद चालू — बंद करें (केवल अरबी)", id: "Terjemahan aktif — matikan (Arab saja)", bn: "অনুবাদ চালু — বন্ধ করুন (শুধু আরবি)", tr: "Meal açık — kapat (yalnızca Arapça)", fr: "Traduction activée — désactiver (arabe seul)", ms: "Terjemahan hidup — matikan (Arab sahaja)" },
  "Translation off — turn on": { ta: "மொழிபெயர்ப்பு இல்லை — இயக்கு", ur: "ترجمہ بند — آن کریں", ml: "പരിഭാഷ ഓഫ് — ഓണാക്കുക", hi: "अनुवाद बंद — चालू करें", id: "Terjemahan mati — nyalakan", bn: "অনুবাদ বন্ধ — চালু করুন", tr: "Meal kapalı — aç", fr: "Traduction désactivée — activer", ms: "Terjemahan mati — hidupkan" },
  On: { ta: "உள்ளது", ur: "آن", ml: "ഓൺ", hi: "चालू", id: "Aktif", bn: "চালু", tr: "Açık", fr: "Activé", ms: "Hidup" },
  Off: { ta: "இல்லை", ur: "بند", ml: "ഓഫ്", hi: "बंद", id: "Mati", bn: "বন্ধ", tr: "Kapalı", fr: "Désactivé", ms: "Mati" },
  "Close translation languages": { ta: "மொழிப் பட்டியலை மூடு", ur: "ترجمے کی زبانیں بند کریں", ml: "പരിഭാഷാ ഭാഷകൾ അടയ്ക്കുക", hi: "अनुवाद भाषाएँ बंद करें", id: "Tutup bahasa terjemahan", bn: "অনুবাদের ভাষা বন্ধ করুন", tr: "Meal dillerini kapat", fr: "Fermer les langues de traduction", ms: "Tutup bahasa terjemahan" },
  "Search languages...": { ta: "மொழிகளைத் தேடு...", ur: "زبانیں تلاش کریں...", ml: "ഭാഷകൾ തിരയുക...", hi: "भाषाएँ खोजें...", id: "Cari bahasa...", bn: "ভাষা খুঁজুন...", tr: "Dil ara...", fr: "Rechercher une langue...", ms: "Cari bahasa..." },
  "Search languages": { ta: "மொழிகளைத் தேடு", ur: "زبانیں تلاش کریں", ml: "ഭാഷകൾ തിരയുക", hi: "भाषाएँ खोजें", id: "Cari bahasa", bn: "ভাষা খুঁজুন", tr: "Dil ara", fr: "Rechercher une langue", ms: "Cari bahasa" },
  "Translation language": { ta: "மொழிபெயர்ப்பு மொழி", ur: "ترجمے کی زبان", ml: "പരിഭാഷാ ഭാഷ", hi: "अनुवाद की भाषा", id: "Bahasa terjemahan", bn: "অনুবাদের ভাষা", tr: "Meal dili", fr: "Langue de traduction", ms: "Bahasa terjemahan" },
  "No language found for “{q}”": { ta: "“{q}” என்ற மொழி இல்லை", ur: "“{q}” کے لیے کوئی زبان نہیں ملی", ml: "“{q}” എന്ന ഭാഷ കണ്ടെത്തിയില്ല", hi: "“{q}” के लिए कोई भाषा नहीं मिली", id: "Tidak ada bahasa untuk “{q}”", bn: "“{q}” নামে কোনো ভাষা পাওয়া যায়নি", tr: "“{q}” için dil bulunamadı", fr: "Aucune langue trouvée pour « {q} »", ms: "Tiada bahasa untuk “{q}”" },

  // ── Header: text size (reading mode) ──
  "Text size": { ta: "எழுத்து அளவு", ur: "متن کا سائز", ml: "അക്ഷര വലുപ്പം", hi: "अक्षर का आकार", id: "Ukuran teks", bn: "লেখার আকার", tr: "Yazı boyutu", fr: "Taille du texte", ms: "Saiz teks" },
  "Text size: {pct}% — change": { ta: "எழுத்து அளவு: {pct}% — மாற்று", ur: "متن کا سائز: {pct}% — بدلیں", ml: "അക്ഷര വലുപ്പം: {pct}% — മാറ്റുക", hi: "अक्षर का आकार: {pct}% — बदलें", id: "Ukuran teks: {pct}% — ubah", bn: "লেখার আকার: {pct}% — বদলান", tr: "Yazı boyutu: %{pct} — değiştir", fr: "Taille du texte : {pct} % — changer", ms: "Saiz teks: {pct}% — tukar" },
  "Smaller text": { ta: "சிறிய எழுத்து", ur: "چھوٹا متن", ml: "ചെറിയ അക്ഷരം", hi: "छोटे अक्षर", id: "Teks lebih kecil", bn: "ছোট লেখা", tr: "Daha küçük yazı", fr: "Texte plus petit", ms: "Teks lebih kecil" },
  "Larger text": { ta: "பெரிய எழுத்து", ur: "بڑا متن", ml: "വലിയ അക്ഷരം", hi: "बड़े अक्षर", id: "Teks lebih besar", bn: "বড় লেখা", tr: "Daha büyük yazı", fr: "Texte plus grand", ms: "Teks lebih besar" },
  Reset: { ta: "மீட்டமை", ur: "ری سیٹ", ml: "പുനഃസജ്ജമാക്കുക", hi: "रीसेट", id: "Atur ulang", bn: "রিসেট", tr: "Sıfırla", fr: "Réinitialiser", ms: "Set semula" },

  // ── Header: Tajweed / script ──
  Tajweed: { ta: "தஜ்வீத்", ur: "تجوید", ml: "തജ്‌വീദ്", hi: "तजवीद", id: "Tajwid", bn: "তাজবীদ", tr: "Tecvid", fr: "Tajweed", ms: "Tajwid" },
  "Tajweed colours": { ta: "தஜ்வீத் வண்ணங்கள்", ur: "تجوید کے رنگ", ml: "തജ്‌വീദ് നിറങ്ങൾ", hi: "तजवीद के रंग", id: "Warna tajwid", bn: "তাজবীদের রং", tr: "Tecvid renkleri", fr: "Couleurs du tajweed", ms: "Warna tajwid" },
  Script: { ta: "எழுத்துரு", ur: "رسم الخط", ml: "ലിപി", hi: "लिपि", id: "Khat", bn: "লিপি", tr: "Hat", fr: "Écriture", ms: "Khat" },
  "Quran script": { ta: "குர்ஆன் எழுத்துரு", ur: "قرآن کا رسم الخط", ml: "ഖുർആൻ ലിപി", hi: "क़ुरआन की लिपि", id: "Khat Al-Qur'an", bn: "কুরআনের লিপি", tr: "Kur'an hattı", fr: "Écriture du Coran", ms: "Khat al-Quran" },
  Uthmani: { ta: "உஸ்மானி", ur: "عثمانی", ml: "ഉസ്മാനി", hi: "उस्मानी", id: "Utsmani", bn: "উসমানী", tr: "Osmanî", fr: "Othmani", ms: "Uthmani" },
  IndoPak: { ta: "இந்தோபாக்", ur: "انڈو پاک", ml: "ഇന്തോപാക്", hi: "इंडोपाक", id: "IndoPak", bn: "ইন্দোপাক", tr: "IndoPak", fr: "IndoPak", ms: "IndoPak" },
  "Uthmani script only": { ta: "உஸ்மானி எழுத்துருவில் மட்டும்", ur: "صرف عثمانی رسم الخط میں", ml: "ഉസ്മാനി ലിപിയിൽ മാത്രം", hi: "केवल उस्मानी लिपि में", id: "Hanya khat Utsmani", bn: "শুধু উসমানী লিপিতে", tr: "Yalnızca Osmanî hatta", fr: "Écriture othmani uniquement", ms: "Khat Uthmani sahaja" },
  // Tajweed legend (TAJWEED_LEGEND .en in lib/data/quranGlyphs)
  "Silent letter": { ta: "உச்சரிக்கப்படாத எழுத்து", ur: "خاموش حرف", ml: "ഉച്ചരിക്കാത്ത അക്ഷരം", hi: "ख़ामोश अक्षर", id: "Huruf tidak dibaca", bn: "নীরব অক্ষর", tr: "Okunmayan harf", fr: "Lettre muette", ms: "Huruf tidak dibaca" },
  "Normal madd (2)": { ta: "இயல்பான மத் (2)", ur: "مدِ طبعی (2)", ml: "സാധാരണ മദ്ദ് (2)", hi: "मद्दे तबई (2)", id: "Mad thabi'i (2)", bn: "মাদ্দে তবয়ী (2)", tr: "Tabii med (2)", fr: "Madd naturel (2)", ms: "Mad asli (2)" },
  "Separated madd (2/4/6)": { ta: "பிரிந்த மத் (2/4/6)", ur: "مدِ منفصل (2/4/6)", ml: "മദ്ദ് മുൻഫസിൽ (2/4/6)", hi: "मद्दे मुनफ़सिल (2/4/6)", id: "Mad jaiz munfashil (2/4/6)", bn: "মাদ্দে মুনফাসিল (2/4/6)", tr: "Med-i munfasıl (2/4/6)", fr: "Madd séparé (2/4/6)", ms: "Mad jaiz munfasil (2/4/6)" },
  "Connected madd (4/5)": { ta: "இணைந்த மத் (4/5)", ur: "مدِ متصل (4/5)", ml: "മദ്ദ് മുത്തസിൽ (4/5)", hi: "मद्दे मुत्तसिल (4/5)", id: "Mad wajib muttashil (4/5)", bn: "মাদ্দে মুত্তাসিল (4/5)", tr: "Med-i muttasıl (4/5)", fr: "Madd lié (4/5)", ms: "Mad wajib muttasil (4/5)" },
  "Necessary madd (6)": { ta: "கட்டாய மத் (6)", ur: "مدِ لازم (6)", ml: "മദ്ദ് ലാസിം (6)", hi: "मद्दे लाज़िम (6)", id: "Mad lazim (6)", bn: "মাদ্দে লাযিম (6)", tr: "Med-i lâzım (6)", fr: "Madd obligatoire (6)", ms: "Mad lazim (6)" },
  "Ghunnah / Ikhfa'": { ta: "குன்னா / இக்ஃபா", ur: "غنہ / اخفاء", ml: "ഗുന്ന / ഇഖ്ഫാഅ്", hi: "ग़ुन्ना / इख़फ़ा", id: "Ghunnah / Ikhfa'", bn: "গুন্নাহ / ইখফা", tr: "Gunne / İhfâ", fr: "Ghunna / Ikhfa'", ms: "Dengung / Ikhfa'" },
  "Qalqalah (echo)": { ta: "கல்கலா (எதிரொலி)", ur: "قلقلہ (گونج)", ml: "ഖൽഖല (പ്രതിധ്വനി)", hi: "क़लक़ला (गूँज)", id: "Qalqalah (pantulan)", bn: "কলকলাহ (প্রতিধ্বনি)", tr: "Kalkale (yankı)", fr: "Qalqala (écho)", ms: "Qalqalah (lantunan)" },
  "Tafkhim (heavy)": { ta: "தஃப்கீம் (கனமான)", ur: "تفخیم (پُر)", ml: "തഫ്ഖീം (കനത്ത)", hi: "तफ़ख़ीम (भारी)", id: "Tafkhim (tebal)", bn: "তাফখীম (ভারী)", tr: "Tefhîm (kalın)", fr: "Tafkhim (lourd)", ms: "Tafkhim (tebal)" },

  // ── Header: reciter ──
  "Reciter · {name}": { ta: "காரி · {name}", ur: "قاری · {name}", ml: "ഖാരി · {name}", hi: "क़ारी · {name}", id: "Qari · {name}", bn: "ক্বারী · {name}", tr: "Kârî · {name}", fr: "Récitateur · {name}", ms: "Qari · {name}" },
  "Choose Quran Reciter (Current: {name})": { ta: "காரியைத் தேர்ந்தெடு (தற்போது: {name})", ur: "قاری چنیں (موجودہ: {name})", ml: "ഖാരിയെ തിരഞ്ഞെടുക്കുക (ഇപ്പോൾ: {name})", hi: "क़ारी चुनें (अभी: {name})", id: "Pilih qari (saat ini: {name})", bn: "ক্বারী বেছে নিন (বর্তমান: {name})", tr: "Kârî seçin (şu an: {name})", fr: "Choisir le récitateur (actuel : {name})", ms: "Pilih qari (semasa: {name})" },
};
export default strings;
