/**
 * GENERATED by scripts/tools/cbr-audio.mjs — do not edit by hand.
 * Word Sync reciter × Surah streams whose master is a VBR MP3, re-encoded to
 * CBR and served from R2 at /audio/quran-cbr/<reciter>/<surah>.mp3 (Chromium
 * seeks VBR MP3s only approximately). Listed only once uploaded and verified.
 */
export const CBR_AUDIO: Record<string, number[]> = {
  "abdulbaset": [2],
  "alafasy": [1, 37, 59, 78, 82],
  "hussary": [6, 26],
  "minshawi": [13],
  "shatri": [41],
  "sudais": [3, 4, 5, 27, 28, 29],
  "tunaiji": [14, 72]
};

/** "<reciter>/<surah>" → version of a re-uploaded copy (the URL gets ?v=N). */
export const CBR_AUDIO_VERSION: Record<string, number> = {};
