/**
 * GENERATED by scripts/qa/repair-timings.cjs — do not edit by hand.
 * Word Sync reciter × Surah pairs whose STREAMED recording doesn't match the
 * recording their Quran.com word timings were measured on (checked acoustically
 * against the real audio). These Surahs play audio-only for that reciter:
 * highlighting from mismatched timings would show the wrong words.
 */
export const WORD_SYNC_UNAVAILABLE: Record<string, Record<number, string>> = {};
